services:
version: '3'
services:
  app:
    image: nombre-de-tu-imagen
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nombre_de_tu_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
